# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Webex Meeting', 'Webex Meeting'), ('Zoom Meeting', 'Zoom Meeting'), ('Regular Meeting', 'Regular Meeting'), ('Seminar', 'Seminar')], default='Regular Meeting', max_length=255)),
                ('content', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Sprint Retrospective', 'Sprint Retrospective'), ('Alignment Meeting', 'Alignment Meeting'), ('Regular Meeting', 'Regular Meeting'), ('Code Review', 'Code Review'), ('Sprint Planning', 'Sprint Planning')], default='Regular Meeting', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
