# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20200510_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Alignment Meeting', 'Alignment Meeting'), ('Code Review', 'Code Review'), ('Sprint Retrospective', 'Sprint Retrospective'), ('Sprint Planning', 'Sprint Planning'), ('Regular Meeting', 'Regular Meeting')], default='Regular Meeting', max_length=50),
        ),
    ]
