# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_auto_20200510_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Code Review', 'Code Review'), ('Sprint Retrospective', 'Sprint Retrospective'), ('Regular Meeting', 'Regular Meeting'), ('Sprint Planning', 'Sprint Planning'), ('Alignment Meeting', 'Alignment Meeting')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('Regular', 'Regular'), ('Seminar', 'Seminar')], default='Regular', max_length=255),
        ),
    ]
