# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_auto_20200510_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Junior Developer', 'Junior Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('Intern', 'Intern'), ('Backend Developer', 'Backend Developer'), ('Project Manager', 'Project Manager'), ('CEO', 'CEO'), ('Scrum Master', 'Scrum Master'), ('Vice CEO', 'Vice CEO'), ('UI/UX Designer', 'UI/UX Designer'), ('Frontend Developer', 'Frontend Developer'), ('All', 'All')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Alignment Meeting', 'Alignment Meeting'), ('Regular Meeting', 'Regular Meeting'), ('Sprint Planning', 'Sprint Planning'), ('Code Review', 'Code Review'), ('Sprint Retrospective', 'Sprint Retrospective')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Seminar', 'Seminar'), ('Online', 'Online')], default='Regular', max_length=255),
        ),
    ]
