# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0014_auto_20200511_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='reply', max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_sender', to=settings.AUTH_USER_MODEL)),
                ('given_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Code Review', 'Code Review'), ('Alignment Meeting', 'Alignment Meeting'), ('Sprint Retrospective', 'Sprint Retrospective'), ('Regular Meeting', 'Regular Meeting'), ('Sprint Planning', 'Sprint Planning')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Backend Developer', 'Backend Developer'), ('Project Manager', 'Project Manager'), ('Scrum Master', 'Scrum Master'), ('All', 'All'), ('Fullstack Developer', 'Fullstack Developer'), ('CEO', 'CEO'), ('Vice CEO', 'Vice CEO'), ('Junior Developer', 'Junior Developer'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Intern', 'Intern')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Regular', 'Regular'), ('Online', 'Online')], default='Regular', max_length=255),
        ),
    ]
