# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0015_auto_20200511_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Regular Meeting', 'Regular Meeting'), ('Sprint Retrospective', 'Sprint Retrospective'), ('Code Review', 'Code Review'), ('Alignment Meeting', 'Alignment Meeting'), ('Sprint Planning', 'Sprint Planning')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('CEO', 'CEO'), ('All', 'All'), ('Intern', 'Intern'), ('Project Manager', 'Project Manager'), ('Vice CEO', 'Vice CEO'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Junior Developer', 'Junior Developer'), ('Scrum Master', 'Scrum Master')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('Seminar', 'Seminar'), ('Regular', 'Regular')], default='Regular', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
