# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0024_auto_20200513_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Alignment Meeting', 'Alignment Meeting'), ('Code Review', 'Code Review'), ('Sprint Retrospective', 'Sprint Retrospective'), ('Regular Meeting', 'Regular Meeting'), ('Sprint Planning', 'Sprint Planning')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('All', 'All'), ('UI/UX Designer', 'UI/UX Designer'), ('Fullstack Developer', 'Fullstack Developer'), ('Backend Developer', 'Backend Developer'), ('Project Manager', 'Project Manager'), ('CEO', 'CEO'), ('Frontend Developer', 'Frontend Developer'), ('Junior Developer', 'Junior Developer'), ('Vice CEO', 'Vice CEO'), ('Intern', 'Intern'), ('Scrum Master', 'Scrum Master')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('Regular', 'Regular'), ('Seminar', 'Seminar')], default='Regular', max_length=255),
        ),
    ]
