# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0025_auto_20200513_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Regular Meeting', 'Regular Meeting'), ('Sprint Retrospective', 'Sprint Retrospective'), ('Code Review', 'Code Review'), ('Alignment Meeting', 'Alignment Meeting'), ('Sprint Planning', 'Sprint Planning')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Frontend Developer', 'Frontend Developer'), ('CEO', 'CEO'), ('Fullstack Developer', 'Fullstack Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Vice CEO', 'Vice CEO'), ('Junior Developer', 'Junior Developer'), ('Backend Developer', 'Backend Developer'), ('Intern', 'Intern'), ('Project Manager', 'Project Manager'), ('Scrum Master', 'Scrum Master'), ('All', 'All')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Online', 'Online'), ('Regular', 'Regular')], default='Regular', max_length=255),
        ),
    ]
