# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0026_auto_20200513_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='attendance_status',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Sprint Retrospective', 'Sprint Retrospective'), ('Alignment Meeting', 'Alignment Meeting'), ('Regular Meeting', 'Regular Meeting'), ('Code Review', 'Code Review'), ('Sprint Planning', 'Sprint Planning')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('UI/UX Designer', 'UI/UX Designer'), ('Junior Developer', 'Junior Developer'), ('Vice CEO', 'Vice CEO'), ('Scrum Master', 'Scrum Master'), ('Intern', 'Intern'), ('All', 'All'), ('Frontend Developer', 'Frontend Developer'), ('Project Manager', 'Project Manager'), ('Fullstack Developer', 'Fullstack Developer'), ('CEO', 'CEO'), ('Backend Developer', 'Backend Developer')], default='All', max_length=50),
        ),
    ]
