# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0028_auto_20200513_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Regular Meeting', 'Regular Meeting'), ('Alignment Meeting', 'Alignment Meeting'), ('Sprint Retrospective', 'Sprint Retrospective'), ('Sprint Planning', 'Sprint Planning'), ('Code Review', 'Code Review')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('UI/UX Designer', 'UI/UX Designer'), ('Intern', 'Intern'), ('CEO', 'CEO'), ('Frontend Developer', 'Frontend Developer'), ('Project Manager', 'Project Manager'), ('Vice CEO', 'Vice CEO'), ('Scrum Master', 'Scrum Master'), ('Fullstack Developer', 'Fullstack Developer'), ('Backend Developer', 'Backend Developer'), ('All', 'All'), ('Junior Developer', 'Junior Developer')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('Seminar', 'Seminar'), ('Regular', 'Regular')], default='Regular', max_length=255),
        ),
    ]
