# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0034_auto_20200516_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Sprint Retrospective', 'Sprint Retrospective'), ('Sprint Planning', 'Sprint Planning'), ('Alignment Meeting', 'Alignment Meeting'), ('Code Review', 'Code Review'), ('Regular Meeting', 'Regular Meeting')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Scrum Master', 'Scrum Master'), ('Intern', 'Intern'), ('Backend Developer', 'Backend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('All', 'All'), ('Frontend Developer', 'Frontend Developer'), ('Project Manager', 'Project Manager'), ('Vice CEO', 'Vice CEO'), ('CEO', 'CEO'), ('UI/UX Designer', 'UI/UX Designer'), ('Junior Developer', 'Junior Developer')], default='All', max_length=50),
        ),
    ]
