# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0035_auto_20200615_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Sprint Planning', 'Sprint Planning'), ('Alignment Meeting', 'Alignment Meeting'), ('Regular Meeting', 'Regular Meeting'), ('Code Review', 'Code Review'), ('Sprint Retrospective', 'Sprint Retrospective')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Junior Developer', 'Junior Developer'), ('Scrum Master', 'Scrum Master'), ('Project Manager', 'Project Manager'), ('Fullstack Developer', 'Fullstack Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('CEO', 'CEO'), ('Frontend Developer', 'Frontend Developer'), ('Intern', 'Intern'), ('All', 'All'), ('Vice CEO', 'Vice CEO'), ('Backend Developer', 'Backend Developer')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Online', 'Online'), ('Seminar', 'Seminar')], default='Regular', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
