# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0036_auto_20200615_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Alignment Meeting', 'Alignment Meeting'), ('Sprint Planning', 'Sprint Planning'), ('Regular Meeting', 'Regular Meeting'), ('Code Review', 'Code Review'), ('Sprint Retrospective', 'Sprint Retrospective')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Frontend Developer', 'Frontend Developer'), ('All', 'All'), ('CEO', 'CEO'), ('Intern', 'Intern'), ('UI/UX Designer', 'UI/UX Designer'), ('Backend Developer', 'Backend Developer'), ('Project Manager', 'Project Manager'), ('Scrum Master', 'Scrum Master'), ('Vice CEO', 'Vice CEO'), ('Fullstack Developer', 'Fullstack Developer'), ('Junior Developer', 'Junior Developer')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('Regular', 'Regular'), ('Seminar', 'Seminar')], default='Regular', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
