# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0037_auto_20200615_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Regular Meeting', 'Regular Meeting'), ('Sprint Planning', 'Sprint Planning'), ('Sprint Retrospective', 'Sprint Retrospective'), ('Alignment Meeting', 'Alignment Meeting'), ('Code Review', 'Code Review')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Vice CEO', 'Vice CEO'), ('Scrum Master', 'Scrum Master'), ('Intern', 'Intern'), ('All', 'All'), ('Project Manager', 'Project Manager'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Junior Developer', 'Junior Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('CEO', 'CEO'), ('Fullstack Developer', 'Fullstack Developer')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
