# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0038_auto_20200615_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Code Review', 'Code Review'), ('Alignment Meeting', 'Alignment Meeting'), ('Sprint Retrospective', 'Sprint Retrospective'), ('Sprint Planning', 'Sprint Planning'), ('Regular Meeting', 'Regular Meeting')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Fullstack Developer', 'Fullstack Developer'), ('Frontend Developer', 'Frontend Developer'), ('Scrum Master', 'Scrum Master'), ('Vice CEO', 'Vice CEO'), ('CEO', 'CEO'), ('UI/UX Designer', 'UI/UX Designer'), ('Intern', 'Intern'), ('All', 'All'), ('Backend Developer', 'Backend Developer'), ('Junior Developer', 'Junior Developer')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Online', 'Online'), ('Seminar', 'Seminar')], default='Regular', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
