# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0039_auto_20200615_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_sender', to=settings.AUTH_USER_MODEL)),
                ('given_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Sprint Planning', 'Sprint Planning'), ('Regular Meeting', 'Regular Meeting'), ('Alignment Meeting', 'Alignment Meeting'), ('Code Review', 'Code Review'), ('Sprint Retrospective', 'Sprint Retrospective')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('UI/UX Designer', 'UI/UX Designer'), ('CEO', 'CEO'), ('Scrum Master', 'Scrum Master'), ('Frontend Developer', 'Frontend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('All', 'All'), ('Vice CEO', 'Vice CEO'), ('Backend Developer', 'Backend Developer'), ('Project Manager', 'Project Manager'), ('Junior Developer', 'Junior Developer'), ('Intern', 'Intern')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('Regular', 'Regular'), ('Seminar', 'Seminar')], default='Regular', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Deadline (mm/dd/yyyy)'),
        ),
        migrations.AddField(
            model_name='taskreporthistory',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_history', to='Employee.Task'),
        ),
    ]
