# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0040_auto_20200708_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreporthistory',
            name='sent_at',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Alignment Meeting', 'Alignment Meeting'), ('Code Review', 'Code Review'), ('Regular Meeting', 'Regular Meeting'), ('Sprint Planning', 'Sprint Planning'), ('Sprint Retrospective', 'Sprint Retrospective')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Backend Developer', 'Backend Developer'), ('All', 'All'), ('Junior Developer', 'Junior Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('CEO', 'CEO'), ('Frontend Developer', 'Frontend Developer'), ('Scrum Master', 'Scrum Master'), ('Vice CEO', 'Vice CEO'), ('Project Manager', 'Project Manager'), ('Intern', 'Intern'), ('UI/UX Designer', 'UI/UX Designer')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('Seminar', 'Seminar'), ('Regular', 'Regular')], default='Regular', max_length=255),
        ),
    ]
