# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employee', '0046_auto_20200719_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='given_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Code Review', 'Code Review'), ('Alignment Meeting', 'Alignment Meeting'), ('Sprint Retrospective', 'Sprint Retrospective'), ('Regular Meeting', 'Regular Meeting'), ('Sprint Planning', 'Sprint Planning')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Fullstack Developer', 'Fullstack Developer'), ('Intern', 'Intern'), ('Project Manager', 'Project Manager'), ('Backend Developer', 'Backend Developer'), ('CEO', 'CEO'), ('All', 'All'), ('Vice CEO', 'Vice CEO'), ('Scrum Master', 'Scrum Master'), ('Junior Developer', 'Junior Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Frontend Developer', 'Frontend Developer')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date (mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Time (hh:mm)'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('Regular', 'Regular'), ('Seminar', 'Seminar')], default='Regular', max_length=255),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_set', to='Employee.Task'),
        ),
    ]
