# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0047_auto_20200721_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Sprint Planning', 'Sprint Planning'), ('Regular Meeting', 'Regular Meeting'), ('Sprint Retrospective', 'Sprint Retrospective'), ('Code Review', 'Code Review'), ('Alignment Meeting', 'Alignment Meeting')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Backend Developer', 'Backend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('Intern', 'Intern'), ('UI/UX Designer', 'UI/UX Designer'), ('Project Manager', 'Project Manager'), ('Junior Developer', 'Junior Developer'), ('All', 'All'), ('Frontend Developer', 'Frontend Developer'), ('Scrum Master', 'Scrum Master'), ('CEO', 'CEO'), ('Vice CEO', 'Vice CEO')], default='All', max_length=50),
        ),
    ]
