# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-07 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0048_auto_20200907_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Regular Meeting', 'Regular Meeting'), ('Alignment Meeting', 'Alignment Meeting'), ('Code Review', 'Code Review'), ('Sprint Planning', 'Sprint Planning'), ('Sprint Retrospective', 'Sprint Retrospective')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('All', 'All'), ('UI/UX Designer', 'UI/UX Designer'), ('Fullstack Developer', 'Fullstack Developer'), ('Intern', 'Intern'), ('Backend Developer', 'Backend Developer'), ('CEO', 'CEO'), ('Scrum Master', 'Scrum Master'), ('Junior Developer', 'Junior Developer'), ('Vice CEO', 'Vice CEO'), ('Frontend Developer', 'Frontend Developer')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Regular', 'Regular'), ('Online', 'Online')], default='Regular', max_length=255),
        ),
    ]
