# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0049_auto_20200907_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Code Review', 'Code Review'), ('Sprint Retrospective', 'Sprint Retrospective'), ('Alignment Meeting', 'Alignment Meeting'), ('Regular Meeting', 'Regular Meeting'), ('Sprint Planning', 'Sprint Planning')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Backend Developer', 'Backend Developer'), ('Project Manager', 'Project Manager'), ('Vice CEO', 'Vice CEO'), ('All', 'All'), ('CEO', 'CEO'), ('Junior Developer', 'Junior Developer'), ('Scrum Master', 'Scrum Master'), ('Fullstack Developer', 'Fullstack Developer'), ('Intern', 'Intern'), ('UI/UX Designer', 'UI/UX Designer'), ('Frontend Developer', 'Frontend Developer')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('Regular', 'Regular'), ('Seminar', 'Seminar')], default='Regular', max_length=255),
        ),
    ]
