# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0050_auto_20201023_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Alignment Meeting', 'Alignment Meeting'), ('Regular Meeting', 'Regular Meeting'), ('Sprint Planning', 'Sprint Planning'), ('Code Review', 'Code Review'), ('Sprint Retrospective', 'Sprint Retrospective')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Vice CEO', 'Vice CEO'), ('Project Manager', 'Project Manager'), ('CEO', 'CEO'), ('Fullstack Developer', 'Fullstack Developer'), ('Intern', 'Intern'), ('All', 'All'), ('Junior Developer', 'Junior Developer'), ('Scrum Master', 'Scrum Master'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Backend Developer', 'Backend Developer')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('Online', 'Online'), ('Seminar', 'Seminar'), ('Regular', 'Regular')], default='Regular', max_length=255),
        ),
    ]
