# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-02 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0054_auto_20201202_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.CharField(choices=[('Code Review', 'Code Review'), ('Regular Meeting', 'Regular Meeting'), ('Sprint Planning', 'Sprint Planning'), ('Alignment Meeting', 'Alignment Meeting'), ('Sprint Retrospective', 'Sprint Retrospective')], default='Regular Meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(choices=[('Vice CEO', 'Vice CEO'), ('Intern', 'Intern'), ('Project Manager', 'Project Manager'), ('CEO', 'CEO'), ('Fullstack Developer', 'Fullstack Developer'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('All', 'All'), ('Junior Developer', 'Junior Developer'), ('Backend Developer', 'Backend Developer'), ('Scrum Master', 'Scrum Master')], default='All', max_length=50),
        ),
    ]
