# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('position', models.CharField(choices=[('Frontend Developer', 'Frontend Developer'), ('Scrum Master', 'Scrum Master'), ('Backend Developer', 'Backend Developer'), ('Junior Developer', 'Junior Developer'), ('Intern', 'Intern'), ('UI/UX Designer', 'UI/UX Designer'), ('Vice CEO', 'Vice CEO'), ('Fullstack Developer', 'Fullstack Developer'), ('CEO', 'CEO'), ('Project Manager', 'Project Manager')], default='Junior Developer', max_length=50)),
                ('profile_pic', models.ImageField(blank=True, default='social.png', null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
