# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Junior Developer', 'Junior Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('Vice CEO', 'Vice CEO'), ('Frontend Developer', 'Frontend Developer'), ('Scrum Master', 'Scrum Master'), ('Backend Developer', 'Backend Developer'), ('Intern', 'Intern'), ('UI/UX Designer', 'UI/UX Designer'), ('CEO', 'CEO')], default='Junior Developer', max_length=50),
        ),
    ]
