# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20200508_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('Fullstack Developer', 'Fullstack Developer'), ('CEO', 'CEO'), ('Backend Developer', 'Backend Developer'), ('Junior Developer', 'Junior Developer'), ('Project Manager', 'Project Manager'), ('Vice CEO', 'Vice CEO'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Scrum Master', 'Scrum Master'), ('Intern', 'Intern')], default='Junior Developer', max_length=50),
        ),
    ]
