# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20200508_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('Fullstack Developer', 'Fullstack Developer'), ('Scrum Master', 'Scrum Master'), ('Project Manager', 'Project Manager'), ('Backend Developer', 'Backend Developer'), ('Vice CEO', 'Vice CEO'), ('Intern', 'Intern'), ('UI/UX Designer', 'UI/UX Designer'), ('CEO', 'CEO'), ('Frontend Developer', 'Frontend Developer'), ('Junior Developer', 'Junior Developer')], default='Junior Developer', max_length=50),
        ),
    ]
