# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_auto_20200508_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Fullstack Developer', 'Fullstack Developer'), ('Project Manager', 'Project Manager'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Junior Developer', 'Junior Developer'), ('Intern', 'Intern'), ('Scrum Master', 'Scrum Master'), ('Backend Developer', 'Backend Developer'), ('Vice CEO', 'Vice CEO')], default='Junior Developer', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
