# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_auto_20200508_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('UI/UX Designer', 'UI/UX Designer'), ('Backend Developer', 'Backend Developer'), ('Scrum Master', 'Scrum Master'), ('Junior Developer', 'Junior Developer'), ('Frontend Developer', 'Frontend Developer'), ('Intern', 'Intern'), ('Vice CEO', 'Vice CEO'), ('CEO', 'CEO'), ('Fullstack Developer', 'Fullstack Developer'), ('Project Manager', 'Project Manager')], default='Junior Developer', max_length=50),
        ),
    ]
