# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0024_auto_20200509_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Scrum Master', 'Scrum Master'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Vice CEO', 'Vice CEO'), ('CEO', 'CEO'), ('Junior Developer', 'Junior Developer'), ('Project Manager', 'Project Manager'), ('Intern', 'Intern'), ('Backend Developer', 'Backend Developer'), ('Fullstack Developer', 'Fullstack Developer')], default='Junior Developer', max_length=50),
        ),
    ]
