# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0025_auto_20200509_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('UI/UX Designer', 'UI/UX Designer'), ('Junior Developer', 'Junior Developer'), ('Backend Developer', 'Backend Developer'), ('Intern', 'Intern'), ('Fullstack Developer', 'Fullstack Developer'), ('Frontend Developer', 'Frontend Developer'), ('Project Manager', 'Project Manager'), ('Scrum Master', 'Scrum Master'), ('CEO', 'CEO'), ('Vice CEO', 'Vice CEO')], default='Junior Developer', max_length=50),
        ),
    ]
