# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0027_auto_20200509_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('UI/UX Designer', 'UI/UX Designer'), ('Backend Developer', 'Backend Developer'), ('CEO', 'CEO'), ('Scrum Master', 'Scrum Master'), ('Frontend Developer', 'Frontend Developer'), ('Vice CEO', 'Vice CEO'), ('Junior Developer', 'Junior Developer'), ('Intern', 'Intern'), ('Fullstack Developer', 'Fullstack Developer'), ('Project Manager', 'Project Manager')], default='Junior Developer', max_length=50),
        ),
    ]
