# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0028_auto_20200509_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Junior Developer', 'Junior Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Project Manager', 'Project Manager'), ('CEO', 'CEO'), ('Frontend Developer', 'Frontend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('Vice CEO', 'Vice CEO'), ('Backend Developer', 'Backend Developer'), ('Intern', 'Intern'), ('Scrum Master', 'Scrum Master')], default='Junior Developer', max_length=50),
        ),
    ]
