# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0029_auto_20200509_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Junior Developer', 'Junior Developer'), ('Backend Developer', 'Backend Developer'), ('Vice CEO', 'Vice CEO'), ('Intern', 'Intern'), ('Fullstack Developer', 'Fullstack Developer'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Project Manager', 'Project Manager'), ('Scrum Master', 'Scrum Master'), ('CEO', 'CEO')], default='Junior Developer', max_length=50),
        ),
    ]
