# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0030_auto_20200509_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Vice CEO', 'Vice CEO'), ('Intern', 'Intern'), ('Junior Developer', 'Junior Developer'), ('Backend Developer', 'Backend Developer'), ('CEO', 'CEO'), ('Scrum Master', 'Scrum Master'), ('Frontend Developer', 'Frontend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Project Manager', 'Project Manager')], default='Junior Developer', max_length=50),
        ),
    ]
