# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0031_auto_20200509_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('UI/UX Designer', 'UI/UX Designer'), ('Junior Developer', 'Junior Developer'), ('Intern', 'Intern'), ('CEO', 'CEO'), ('Vice CEO', 'Vice CEO'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('Scrum Master', 'Scrum Master'), ('Project Manager', 'Project Manager')], default='Junior Developer', max_length=50),
        ),
    ]
