# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0034_auto_20200510_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('CEO', 'CEO'), ('Junior Developer', 'Junior Developer'), ('Backend Developer', 'Backend Developer'), ('Intern', 'Intern'), ('UI/UX Designer', 'UI/UX Designer'), ('Scrum Master', 'Scrum Master'), ('Fullstack Developer', 'Fullstack Developer'), ('Frontend Developer', 'Frontend Developer'), ('Vice CEO', 'Vice CEO')], default='Junior Developer', max_length=50),
        ),
    ]
