# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0039_auto_20200510_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Junior Developer', 'Junior Developer'), ('Frontend Developer', 'Frontend Developer'), ('CEO', 'CEO'), ('Fullstack Developer', 'Fullstack Developer'), ('Project Manager', 'Project Manager'), ('Intern', 'Intern'), ('Vice CEO', 'Vice CEO'), ('Scrum Master', 'Scrum Master'), ('UI/UX Designer', 'UI/UX Designer'), ('Backend Developer', 'Backend Developer')], default='Junior Developer', max_length=50),
        ),
    ]
