# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0040_auto_20200510_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Vice CEO', 'Vice CEO'), ('Junior Developer', 'Junior Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Project Manager', 'Project Manager'), ('Frontend Developer', 'Frontend Developer'), ('Scrum Master', 'Scrum Master'), ('CEO', 'CEO'), ('Fullstack Developer', 'Fullstack Developer'), ('Backend Developer', 'Backend Developer')], default='Junior Developer', max_length=50),
        ),
    ]
