# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0041_auto_20200510_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Scrum Master', 'Scrum Master'), ('Vice CEO', 'Vice CEO'), ('CEO', 'CEO'), ('Junior Developer', 'Junior Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Intern', 'Intern'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Project Manager', 'Project Manager'), ('Fullstack Developer', 'Fullstack Developer')], default='Junior Developer', max_length=50),
        ),
    ]
