# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0042_auto_20200510_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Junior Developer', 'Junior Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('Intern', 'Intern'), ('Backend Developer', 'Backend Developer'), ('Project Manager', 'Project Manager'), ('CEO', 'CEO'), ('Scrum Master', 'Scrum Master'), ('Vice CEO', 'Vice CEO'), ('UI/UX Designer', 'UI/UX Designer'), ('Frontend Developer', 'Frontend Developer')], default='Junior Developer', max_length=50),
        ),
    ]
