# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0045_auto_20200511_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Backend Developer', 'Backend Developer'), ('Project Manager', 'Project Manager'), ('Scrum Master', 'Scrum Master'), ('Fullstack Developer', 'Fullstack Developer'), ('CEO', 'CEO'), ('Vice CEO', 'Vice CEO'), ('Junior Developer', 'Junior Developer'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Intern', 'Intern')], default='Junior Developer', max_length=50),
        ),
    ]
