# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0046_auto_20200511_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Intern', 'Intern'), ('Project Manager', 'Project Manager'), ('Vice CEO', 'Vice CEO'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Junior Developer', 'Junior Developer'), ('Scrum Master', 'Scrum Master')], default='Junior Developer', max_length=50),
        ),
    ]
