# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0047_auto_20200511_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Scrum Master', 'Scrum Master'), ('Frontend Developer', 'Frontend Developer'), ('Intern', 'Intern'), ('CEO', 'CEO'), ('UI/UX Designer', 'UI/UX Designer'), ('Fullstack Developer', 'Fullstack Developer'), ('Vice CEO', 'Vice CEO'), ('Backend Developer', 'Backend Developer'), ('Junior Developer', 'Junior Developer'), ('Project Manager', 'Project Manager')], default='Junior Developer', max_length=50),
        ),
    ]
