# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0050_auto_20200512_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Fullstack Developer', 'Fullstack Developer'), ('Vice CEO', 'Vice CEO'), ('Frontend Developer', 'Frontend Developer'), ('Intern', 'Intern'), ('Scrum Master', 'Scrum Master'), ('Project Manager', 'Project Manager'), ('Junior Developer', 'Junior Developer'), ('CEO', 'CEO'), ('UI/UX Designer', 'UI/UX Designer'), ('Backend Developer', 'Backend Developer')], default='Junior Developer', max_length=50),
        ),
    ]
