# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0051_auto_20200512_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Frontend Developer', 'Frontend Developer'), ('Scrum Master', 'Scrum Master'), ('UI/UX Designer', 'UI/UX Designer'), ('Vice CEO', 'Vice CEO'), ('Junior Developer', 'Junior Developer'), ('CEO', 'CEO'), ('Backend Developer', 'Backend Developer'), ('Intern', 'Intern'), ('Fullstack Developer', 'Fullstack Developer'), ('Project Manager', 'Project Manager')], default='Junior Developer', max_length=50),
        ),
    ]
