# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0053_auto_20200513_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Junior Developer', 'Junior Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Frontend Developer', 'Frontend Developer'), ('Project Manager', 'Project Manager'), ('Scrum Master', 'Scrum Master'), ('Backend Developer', 'Backend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('CEO', 'CEO'), ('Intern', 'Intern'), ('Vice CEO', 'Vice CEO')], default='Junior Developer', max_length=50),
        ),
    ]
