# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0054_auto_20200513_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Intern', 'Intern'), ('UI/UX Designer', 'UI/UX Designer'), ('CEO', 'CEO'), ('Backend Developer', 'Backend Developer'), ('Project Manager', 'Project Manager'), ('Vice CEO', 'Vice CEO'), ('Scrum Master', 'Scrum Master'), ('Junior Developer', 'Junior Developer'), ('Frontend Developer', 'Frontend Developer'), ('Fullstack Developer', 'Fullstack Developer')], default='Junior Developer', max_length=50),
        ),
    ]
