# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0059_auto_20200513_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('UI/UX Designer', 'UI/UX Designer'), ('Intern', 'Intern'), ('CEO', 'CEO'), ('Frontend Developer', 'Frontend Developer'), ('Project Manager', 'Project Manager'), ('Vice CEO', 'Vice CEO'), ('Scrum Master', 'Scrum Master'), ('Fullstack Developer', 'Fullstack Developer'), ('Backend Developer', 'Backend Developer'), ('Junior Developer', 'Junior Developer')], default='Junior Developer', max_length=50),
        ),
    ]
