# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0060_auto_20200513_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Backend Developer', 'Backend Developer'), ('Junior Developer', 'Junior Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('CEO', 'CEO'), ('Scrum Master', 'Scrum Master'), ('UI/UX Designer', 'UI/UX Designer'), ('Frontend Developer', 'Frontend Developer'), ('Vice CEO', 'Vice CEO'), ('Project Manager', 'Project Manager'), ('Intern', 'Intern')], default='Junior Developer', max_length=50),
        ),
    ]
