# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0062_auto_20200513_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('UI/UX Designer', 'UI/UX Designer'), ('Fullstack Developer', 'Fullstack Developer'), ('Junior Developer', 'Junior Developer'), ('Scrum Master', 'Scrum Master'), ('Intern', 'Intern'), ('Vice CEO', 'Vice CEO'), ('CEO', 'CEO'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Project Manager', 'Project Manager')], default='Junior Developer', max_length=50),
        ),
    ]
