# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0065_auto_20200513_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Backend Developer', 'Backend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('Junior Developer', 'Junior Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Scrum Master', 'Scrum Master'), ('Vice CEO', 'Vice CEO'), ('Frontend Developer', 'Frontend Developer'), ('Project Manager', 'Project Manager'), ('CEO', 'CEO'), ('Intern', 'Intern')], default='Junior Developer', max_length=50),
        ),
    ]
