# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0066_auto_20200513_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Fullstack Developer', 'Fullstack Developer'), ('Project Manager', 'Project Manager'), ('Intern', 'Intern'), ('CEO', 'CEO'), ('Vice CEO', 'Vice CEO'), ('Junior Developer', 'Junior Developer'), ('Scrum Master', 'Scrum Master'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer')], default='Junior Developer', max_length=50),
        ),
    ]
