# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0072_auto_20200615_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Junior Developer', 'Junior Developer'), ('Scrum Master', 'Scrum Master'), ('Project Manager', 'Project Manager'), ('Fullstack Developer', 'Fullstack Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('CEO', 'CEO'), ('Frontend Developer', 'Frontend Developer'), ('Intern', 'Intern'), ('Vice CEO', 'Vice CEO'), ('Backend Developer', 'Backend Developer')], default='Junior Developer', max_length=50),
        ),
    ]
