# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0075_auto_20200615_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Fullstack Developer', 'Fullstack Developer'), ('Frontend Developer', 'Frontend Developer'), ('Scrum Master', 'Scrum Master'), ('Vice CEO', 'Vice CEO'), ('CEO', 'CEO'), ('UI/UX Designer', 'UI/UX Designer'), ('Intern', 'Intern'), ('Backend Developer', 'Backend Developer'), ('Junior Developer', 'Junior Developer')], default='Junior Developer', max_length=50),
        ),
    ]
