# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0077_auto_20200708_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Backend Developer', 'Backend Developer'), ('Junior Developer', 'Junior Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('CEO', 'CEO'), ('Frontend Developer', 'Frontend Developer'), ('Scrum Master', 'Scrum Master'), ('Vice CEO', 'Vice CEO'), ('Project Manager', 'Project Manager'), ('Intern', 'Intern'), ('UI/UX Designer', 'UI/UX Designer')], default='Junior Developer', max_length=50),
        ),
    ]
