# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-12 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0081_auto_20200711_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Vice CEO', 'Vice CEO'), ('Junior Developer', 'Junior Developer'), ('Backend Developer', 'Backend Developer'), ('Project Manager', 'Project Manager'), ('CEO', 'CEO'), ('Scrum Master', 'Scrum Master'), ('Intern', 'Intern'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Fullstack Developer', 'Fullstack Developer')], default='Junior Developer', max_length=50),
        ),
    ]
