# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0083_auto_20200719_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Fullstack Developer', 'Fullstack Developer'), ('Intern', 'Intern'), ('Project Manager', 'Project Manager'), ('Backend Developer', 'Backend Developer'), ('CEO', 'CEO'), ('Vice CEO', 'Vice CEO'), ('Scrum Master', 'Scrum Master'), ('Junior Developer', 'Junior Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Frontend Developer', 'Frontend Developer')], default='Junior Developer', max_length=50),
        ),
    ]
