# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-07 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0084_auto_20200721_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('UI/UX Designer', 'UI/UX Designer'), ('Fullstack Developer', 'Fullstack Developer'), ('Intern', 'Intern'), ('Backend Developer', 'Backend Developer'), ('CEO', 'CEO'), ('Scrum Master', 'Scrum Master'), ('Junior Developer', 'Junior Developer'), ('Vice CEO', 'Vice CEO'), ('Frontend Developer', 'Frontend Developer')], default='Junior Developer', max_length=50),
        ),
    ]
