# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0085_auto_20200907_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Backend Developer', 'Backend Developer'), ('Project Manager', 'Project Manager'), ('Vice CEO', 'Vice CEO'), ('CEO', 'CEO'), ('Junior Developer', 'Junior Developer'), ('Scrum Master', 'Scrum Master'), ('Fullstack Developer', 'Fullstack Developer'), ('Intern', 'Intern'), ('UI/UX Designer', 'UI/UX Designer'), ('Frontend Developer', 'Frontend Developer')], default='Junior Developer', max_length=50),
        ),
    ]
