# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0086_auto_20201023_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Vice CEO', 'Vice CEO'), ('Project Manager', 'Project Manager'), ('CEO', 'CEO'), ('Fullstack Developer', 'Fullstack Developer'), ('Intern', 'Intern'), ('Junior Developer', 'Junior Developer'), ('Scrum Master', 'Scrum Master'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Backend Developer', 'Backend Developer')], default='Junior Developer', max_length=50),
        ),
    ]
