# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-19 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0088_auto_20201119_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Fullstack Developer', 'Fullstack Developer'), ('CEO', 'CEO'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Project Manager', 'Project Manager'), ('Scrum Master', 'Scrum Master'), ('Junior Developer', 'Junior Developer'), ('Intern', 'Intern'), ('Vice CEO', 'Vice CEO')], default='Junior Developer', max_length=50),
        ),
    ]
