# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-02 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0089_auto_20201119_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Vice CEO', 'Vice CEO'), ('Frontend Developer', 'Frontend Developer'), ('Intern', 'Intern'), ('Project Manager', 'Project Manager'), ('Junior Developer', 'Junior Developer'), ('CEO', 'CEO'), ('Fullstack Developer', 'Fullstack Developer'), ('Scrum Master', 'Scrum Master'), ('Backend Developer', 'Backend Developer'), ('UI/UX Designer', 'UI/UX Designer')], default='Junior Developer', max_length=50),
        ),
    ]
