# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-02 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0091_auto_20201202_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Backend Developer', 'Backend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('Scrum Master', 'Scrum Master'), ('Junior Developer', 'Junior Developer'), ('Project Manager', 'Project Manager'), ('Frontend Developer', 'Frontend Developer'), ('Vice CEO', 'Vice CEO'), ('CEO', 'CEO'), ('UI/UX Designer', 'UI/UX Designer'), ('Intern', 'Intern')], default='Junior Developer', max_length=50),
        ),
    ]
