# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 04:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0002_auto_20200509_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Other', 'Other'), ('Announcement', 'Announcement'), ('Jobdesc', 'Jobdesc'), ('Meeting', 'Meeting')], default='Jobdesc', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
