# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0003_auto_20200509_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Other', 'Other'), ('Meeting', 'Meeting'), ('Jobdesc', 'Jobdesc'), ('Announcement', 'Announcement')], default='Jobdesc', max_length=50),
        ),
    ]
