# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0006_auto_20200509_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Meeting', 'Meeting'), ('Jobdesc', 'Jobdesc'), ('Other', 'Other'), ('Announcement', 'Announcement')], default='Jobdesc', max_length=50),
        ),
        migrations.AlterField(
            model_name='reply',
            name='replied_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Discussion.Post'),
        ),
    ]
