# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0013_auto_20200510_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Announcement', 'Announcement'), ('Other', 'Other'), ('Jobdesc', 'Jobdesc'), ('Meeting', 'Meeting')], default='Jobdesc', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
