# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0019_auto_20200511_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Jobdesc', 'Jobdesc'), ('Other', 'Other'), ('Announcement', 'Announcement'), ('Meeting', 'Meeting')], default='Jobdesc', max_length=50),
        ),
    ]
