# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0035_auto_20200513_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Meeting', 'Meeting'), ('Announcement', 'Announcement'), ('Other', 'Other'), ('Jobdesc', 'Jobdesc')], default='Jobdesc', max_length=50),
        ),
    ]
