# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-15 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0042_auto_20200515_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Announcement', 'Announcement'), ('Meeting', 'Meeting'), ('Other', 'Other'), ('Jobdesc', 'Jobdesc')], default='Jobdesc', max_length=50),
        ),
    ]
