# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0051_auto_20200708_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Meeting', 'Meeting'), ('Other', 'Other'), ('Jobdesc', 'Jobdesc'), ('Announcement', 'Announcement')], default='Jobdesc', max_length=50),
        ),
    ]
