# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0055_auto_20200712_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Jobdesc', 'Jobdesc'), ('Meeting', 'Meeting'), ('Announcement', 'Announcement'), ('Other', 'Other')], default='Jobdesc', max_length=50),
        ),
    ]
