# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0056_auto_20200719_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Other', 'Other'), ('Jobdesc', 'Jobdesc'), ('Announcement', 'Announcement'), ('Meeting', 'Meeting')], default='Jobdesc', max_length=50),
        ),
    ]
