# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-07 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0058_auto_20200907_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Other', 'Other'), ('Jobdesc', 'Jobdesc'), ('Meeting', 'Meeting'), ('Announcement', 'Announcement')], default='Jobdesc', max_length=50),
        ),
    ]
