# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-02 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0063_auto_20201202_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Announcement', 'Announcement'), ('Jobdesc', 'Jobdesc'), ('Meeting', 'Meeting'), ('Other', 'Other')], default='Jobdesc', max_length=50),
        ),
    ]
